trigger: none
  
  pool:
  name: 'MySelfHostedPool'
  
steps:
- checkout: self

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    architecture: 'x64'

- script: mvn -B package --file pom.xml
  displayName: Build with Maven

- script: mvn deploy
  displayName: Publish Package
