trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

-  task: UseJavaVersion@1
  inputs:
    versionSpec: '11.7'
    architecture: 'x64'

- script: mvn -B package --file pom.xml
  displayName: Build with Maven

- script: mvn deploy
  displayName: Publish Package